FROM alpine

# RUN echo 'date ; sleep 240s ; date ; wget http://jenkins:8080' > /test.sh
RUN echo 'date \n\
sleep 240s \n\
date \n\
wget http://jenkins:8080/metrics/SdQQ16tu23EA94AtNqp_zmMyq0GyO2V85N1TkH4a2BTqeWIFXRZaUq9CqrCrPSqk/ping \n\
' > /test.sh

CMD ["sh", "test.sh"]
