FROM alpine:3.8

RUN set -ex \
  && apk add --no-cache --virtual .fetch-deps \
    curl \
  && echo -e 'date \n\
sleep 240s \n\
date \n\
wget http://jenkins:8080/metrics/SdQQ16tu23EA94AtNqp_zmMyq0GyO2V85N1TkH4a2BTqeWIFXRZaUq9CqrCrPSqk/ping \n\
' > /test.sh \
  && apk del .fetch-deps

ENTRYPOINT ["sh", "test.sh"]
