sut:
  build: .
  dockerfile: dockercloud_autotest/Dockerfile.test
  command: sh /home/autotest_user/test.sh
  links:
    - jenkins

jenkins:
  build: .
  dockerfile: Dockerfile
  ports:
    - 8080:8080
